### ISSUE TITLE
Problema ejecución código tarea

### ISSUE THREAD

**Issue by felumc** [jcontrolresearch/DataStructure#7]
![image](https://user-images.githubusercontent.com/72778813/129987842-914385bd-c134-4aa9-91c9-baf9c6e11eb2.png)
@Hendrick2 @JosiasDH @jcontrolresearch

**Comment by felumc** [comment]
Profe nos marca este error en nuestra ejecución, podría ayudarnos?

**Comment by jcontrolresearch** [comment]
@felumc Estas tratando de usar la estructura Libro como una variable, recuerda que el nombre de la estructura es Lista y la variable puede ser lista o cualquier otro nombre de variable. Intenta usar **lista**
